name: pocket_piano
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^0.1.2
  vibrate: ^0.0.4
  firebase_auth: ^0.15.0+1
  cloud_firestore: ^0.12.10+2
  provider: ^3.2.0
  circular_check_box: ^1.0.1
  flutter_midi: ^1.0.0
  tonic: ^0.2.3
  app_review: ^1.0.0
  intl: ^0.16.0
  font_awesome_flutter: ^8.4.0
  url_launcher: ^5.1.4
  universal_html: ^1.1.6
  bloc: ^0.15.0
  flutter_bloc: ^0.21.0
  firebase_analytics: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:

  uses-material-design: true
  fonts:
    - family: Poppins
      fonts:
        - asset: fonts/Poppins-Regular.ttf
  assets:
    - assets/
    - assets/sf2/Piano.sf2